name: tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: pip install -r requirements.txt
    - run: pip install pytest pre-commit
    - run: pre-commit run --all-files
    # Only run pytest if tests folder exists and has .py files
    - run: |
        if [ -d "tests" ] && ls tests/*.py >/dev/null 2>&1; then
          pytest -q
        else
          echo "No tests found. Skipping pytest."
        fi
